### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by mrgloom** [Smorodov/LogPolarFFTTemplateMatcher#1]
Why do we need to scale input images to [0, 1] interval? I checked it and seems it improves accuracy.

What if we have 2 float images with values of which belong to intervals [a1, b1] and [a2, b2], do we need to scale images separately or together?

Something like this:

```
void ScaleImagesToInterval(const cv::Mat &source, const cv::Mat &target,
        cv::Mat &sourceScaled, cv::Mat &targetScaled)
{
    double sourceMin, sourceMax;
    minMaxLoc(source, &sourceMin, &sourceMax);

    double targetMin, targetMax;
    minMaxLoc(target, &targetMin, &targetMax);

    double min= sourceMin < targetMin ? sourceMin : targetMin;
    double max= sourceMax > targetMax ? sourceMax : targetMax;

    sourceScaled= (source-min) / (max-min);
    targetScaled= (target-min) / (max-min);
} 
```

**Comment by Smorodov** [comment]
I did not checked it, but I see possible issue with such scaling.
If brightest image pixels from one image not fit in window of second image it may make contrast significantly different.  Scale of gray tones for instance. 

But for most cases I think it no sence how to scale images intensities range. If they are taken with same parameters.

May be just whiten them, or use derivatives/edges ?

**Comment by HolaMirai** [comment]
hi Smorodov:
thank you for your work.
i test your code in my computer, when i use the images you privided, the code works, but when i use my own images( .jpg ) ,the code thrown an exception in logpolar() function, as showed below:
![image](https://cloud.githubusercontent.com/assets/13817461/20662009/8e8d5c94-b58c-11e6-958f-5d689c43e324.png)
i checked my images, they are fine and can be read. the difference is my image has only a little translation and some objects in the image moves a little too. no rotation or Scale Invariant.
as showed below, the person moves a little between two images:
![image](https://cloud.githubusercontent.com/assets/13817461/20662138/136fc974-b58d-11e6-92ee-6d96ad418037.png)
![image](https://cloud.githubusercontent.com/assets/13817461/20662125/0989fa6a-b58d-11e6-85d3-502343b38c47.png)
could  it be that  the RST Invariant is too small, so the code thrown the exception ?
best wishes!

**Comment by Smorodov** [comment]
Hi, yes there was swapped rows and cols in logpolar method.
Fixed it now, checked, it works fine with your images.
Thanks for reporting.
