### ISSUE TITLE
cooooool project

### ISSUE THREAD

**Issue by tscmga** [Smorodov/LogPolarFFTTemplateMatcher#12]
so cool. sorry for my poor english
maybe
1.normailize(f0,min_max) normailize the magtiue of dft , i think will make noise bigger
2. add a hanning window to orign image border ,soft image bounder ,may good
3. canny a image , can , change to use gradien of image , that is use sobel to get gx, gy...and to complex, dft..

**Comment by tscmga** [comment]
cv::normalize(f0, f0n, 0, 1, NORM_MINMAX); i think will make noise bigger

**Comment by tscmga** [comment]
and cache the log polar of one image is good ...if...use one template...cache the log polar dft of the template image is good

**Comment by tscmga** [comment]
Mat planes[] = { Mat_<float>(padded), Mat::zeros(padded.size(), CV_32F) };
    Mat complexImg;
    merge(planes, 2, complexImg);
    dft(complexImg, complexImg

set planes[0]=gx planes[1]=gy
i think is the same to canny a image...but less parameters

**Comment by Smorodov** [comment]
Hi, thanks for your notes!
Canny is more complex algorithm and it is not differentiating only, It has postprocessing. 
Really this project is just a base for experiments, post- and pre- processing is highly sensitive to the task you solving. 
Good luck !
