### ISSUE TITLE
Providing an Open Source Licence?

### ISSUE THREAD

**Issue by bojh** [Smorodov/LogPolarFFTTemplateMatcher#13]
First of all, I wanted to thank you for your excellent work. A first test of your implementation shows good results in quality and computing time. 
In order to enable its use in projects with open source management, I would like to ask if you have already considered placing this repo under an open source license? 
Github provides help, see: https://choosealicense.com/. 
I can recommend the MIT license, easy to understand, short and universally applicable. 
Instructions can be found here: https://choosealicense.com/licenses/mit/

Kind regards

**Comment by Smorodov** [comment]
Hi, no problem )
Now it is under MIT License.

**Comment by bojh** [comment]
That was fast. Thank you for your update.
