### ISSUE TITLE
Does this actually work?

### ISSUE THREAD

**Issue by themightyoarfish** [Smorodov/LogPolarFFTTemplateMatcher#8]
I'm a bit confused when looking at the example output:

![FFTTM](https://user-images.githubusercontent.com/11613312/82981539-9048a680-9fec-11ea-8eae-d30526693c7d.PNG)

It seems to me that first of all the template and the target image are almost identical, except for a slight translation and scale difference, but no rotation. Nevertheless, the box shown for the template location exhibits large rotation and appears to be wrong.

Do I not understand the output or does the example not actually show the efficacy of the algorithm?

**Comment by Smorodov** [comment]
Hi, the second image is the same as the image in rotated rectongle from last one, but resized for output them in a row. You can check it by ears crop. The second image is a crop from rotated rectangle. It was output to non-rotated ROI. Tht algorithm works for small offsets, rotations and scale changes. There are also tests to check if it works correct. To get better results image must be contrast and should have a lot of details.
