### ISSUE TITLE
SCORE/CONFIDENCE value

### ISSUE THREAD

**Issue by ManuelSR** [Smorodov/LogPolarFFTTemplateMatcher#9]
Hello,

is there a option to get a score/confidence between model and detection. It could be interesting to use this code for a fast model inspection.

**Comment by Smorodov** [comment]
Hi, as a fast solution you can extract image from source rotated ROI scale it to template size and apply similarity metric. Check https://docs.opencv.org/2.4/doc/tutorials/gpu/gpu-basics-similarity/gpu-basics-similarity.html  for example.

**Comment by ManuelSR** [comment]
Hi, 
OK, i know similarity check. I will try it. But i have just another quick question. Waht is acctually the rate value in templateFinder?
